# Generated by Django 4.2 on 2025-11-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_teacher_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approval_status',
        ),
    ]
